<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<table class="table table-border">
	<tr>
		<th>거래처아이디</th>
		<td>${buyer.buyerId}</td>
	</tr>
	<tr>
		<th>거래처명</th>
		<td>${buyer.buyerName}</td>
	</tr>
	<tr>
		<th>분류명</th>
		<td>${buyer.buyerLgu}</td>
	</tr>
	<tr>
		<th>거래처은행</th>
		<td>${buyer.buyerBank}</td>
	</tr>
	<tr>
		<th>계좌번호</th>
		<td>${buyer.buyerBankno}</td>
	</tr>
	<tr>
		<th>예금주</th>
		<td>${buyer.buyerBankname}</td>
	</tr>
	<tr>
		<th>우편번호</th>
		<td>${buyer.buyerZip}</td>
	</tr>
	<tr>
		<th>주소</th>
		<td>${buyer.buyerAdd1}</td>
	</tr>
	<tr>
		<th>상세주소</th>
		<td>${buyer.buyerAdd2}</td>
	</tr>
	<tr>
		<th>연락처</th>
		<td>${buyer.buyerComtel}</td>
	</tr>
	<tr>
		<th>팩스</th>
		<td>${buyer.buyerFax}</td>
	</tr>
	<tr>
		<th>이메일</th>
		<td>${buyer.buyerMail}</td>
	</tr>
	<tr>
		<th>담당자</th>
		<td>${buyer.buyerCharger}</td>
	</tr>
	<tr>
		<th>내선번호</th>
		<td>${buyer.buyerTelext}</td>
	</tr>
</table>